#!/bin/bash

# ============================================================
# Start Script: Environment Generator & App Launcher
# ============================================================

# 1. Environment Variable Mapping
# Defaults
DB_HOST=${POSTGRES_HOST:-"localhost"}
DB_PORT=${POSTGRES_PORT:-"5432"}
DB_USER=${POSTGRES_USER:-"postgres"}
DB_PASS=${POSTGRES_PASSWORD:-"password"}
DB_NAME=${POSTGRES_DB:-"npm"}
APP_PORT=${PORT:-"3001"}
APP_ENV=${NODE_ENV:-"production"}
APP_TZ=${TZ:-"Asia/Jakarta"}

# 2. URL Encoding for Database Password (Handle special characters like @)
ENCODED_PASS=$(echo -n "$DB_PASS" | python3 -c 'import sys, urllib.parse; print(urllib.parse.quote_plus(sys.stdin.read()))')

# 3. Construct and EXPORT DATABASE_URL
DB_URL="postgresql://${DB_USER}:${ENCODED_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
export DATABASE_URL="$DB_URL"

echo "Constructed DATABASE_URL: postgresql://${DB_USER}:****@${DB_HOST}:${DB_PORT}/${DB_NAME}"

# 3. Generate .env file
# Target path: if running in container /custom-app/.env, else local path
ENV_PATH="./src/app/.env"
if [ -d "/custom-app" ]; then
    ENV_PATH="/custom-app/.env"
fi

echo "Generating .env at $ENV_PATH..."

cat <<EOF > "$ENV_PATH"
# Auto-generated by startScript.sh
DATABASE_URL="$DB_URL"
PORT=$APP_PORT
NODE_ENV=$APP_ENV
TZ=$APP_TZ
EOF

echo ".env generated successfully."

# 4. Container Specific Logic
if [ -d "/custom-app" ]; then
    echo "Running in container mode..."
    cd /custom-app
    
    # Sync Schema using Prisma Migrations (safe for shared databases)
    echo "Running database migrations..."
    
    # Mark the baseline as applied (ignores if already applied) to prevent failure on shared NPM database
    npx prisma migrate resolve --applied 0_baseline || true
    
    npx prisma migrate deploy
    
    # Start Application
    echo "Starting NestJS application..."
    exec node dist/main.js
else
    echo "Running in local mode. .env generated."
    echo "You can now run 'npm run start:dev' in src/app"
fi
