#!/bin/bash

# ============================================================
# Start Script: Environment Generator & App Launcher
# ============================================================

# 1. Environment Variable Mapping & Fallback to Legacy NPM vars
DB_TYPE=${DB_TYPE:-"sqlite"}
DB_HOST=${DB_HOST:-${DB_POSTGRES_HOST:-${DB_MYSQL_HOST:-"localhost"}}}
DB_PORT=${DB_PORT:-${DB_POSTGRES_PORT:-${DB_MYSQL_PORT:-"5432"}}}
DB_USER=${DB_USER:-${DB_POSTGRES_USER:-${DB_MYSQL_USER:-"postgres"}}}
DB_PASS=${DB_PASSWORD:-${DB_POSTGRES_PASSWORD:-${DB_MYSQL_PASSWORD:-"password"}}}
DB_NAME=${DB_NAME:-${DB_POSTGRES_NAME:-${DB_MYSQL_NAME:-"npm"}}}
APP_PORT=${PORT:-"3001"}
APP_ENV=${NODE_ENV:-"production"}
APP_TZ=${TZ:-"Asia/Jakarta"}

# Auto-detect DB_TYPE from NPM legacy env vars if not explicitly set
if [ "$DB_TYPE" = "sqlite" ]; then
    if [ -n "$DB_POSTGRES_HOST" ]; then
        DB_TYPE="postgresql"
        echo "Auto-detected DB_TYPE=postgresql from DB_POSTGRES_HOST"
    elif [ -n "$DB_MYSQL_HOST" ]; then
        DB_TYPE="mysql"
        echo "Auto-detected DB_TYPE=mysql from DB_MYSQL_HOST"
    fi
fi

# SQLite file path
DB_SQLITE_FILE=${DB_SQLITE_FILE:-"/data/custom-lb.sqlite"}

# 2. Generate .env for NestJS application
ENV_PATH="./src/app/.env"
APP_DIR="./src/app"
if [ -d "/custom-app" ]; then
    ENV_PATH="/custom-app/.env"
    APP_DIR="/custom-app"
fi

echo "Generating .env at $ENV_PATH..."
cat <<EOF > "$ENV_PATH"
# Auto-generated by startScript.sh
DB_TYPE=$DB_TYPE
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASS
DB_NAME=$DB_NAME
DB_SQLITE_FILE=$DB_SQLITE_FILE
PORT=$APP_PORT
NODE_ENV=$APP_ENV
TZ=$APP_TZ
EOF
echo ".env generated successfully."

echo "Database engine: $DB_TYPE"
echo "  Host: $DB_HOST:$DB_PORT"
echo "  Database: $DB_NAME"

# 3. Application Run Logic
if [ -d "/custom-app" ]; then
    echo "Running in container mode..."
    cd /custom-app

    # Migration is now handled by NestJS DatabaseService.onModuleInit()
    # No Prisma commands needed!

    # Start Application
    echo "Starting NestJS application..."
    exec node dist/main.js
else
    echo "Running in local mode. .env generated."
    echo "You are using DB_TYPE=$DB_TYPE"
    echo "Start app with 'npm run start:dev' inside src/app."
fi
