#!/bin/bash

# ============================================================
# Start Script: Environment Generator & App Launcher
# ============================================================

# 1. Environment Variable Mapping & Fallback to Legacy POSTGRES_ vars
DB_TYPE=${DB_TYPE:-"postgresql"}
DB_HOST=${DB_HOST:-${POSTGRES_HOST:-"localhost"}}
DB_PORT=${DB_PORT:-${POSTGRES_PORT:-"5432"}}
DB_USER=${DB_USER:-${POSTGRES_USER:-"postgres"}}
DB_PASS=${DB_PASSWORD:-${POSTGRES_PASSWORD:-"password"}}
DB_NAME=${DB_NAME:-${POSTGRES_DB:-"npm"}}
APP_PORT=${PORT:-"3001"}
APP_ENV=${NODE_ENV:-"production"}
APP_TZ=${TZ:-"Asia/Jakarta"}

# URL Encoding for Database Password
ENCODED_PASS=$(echo -n "$DB_PASS" | python3 -c 'import sys, urllib.parse; print(urllib.parse.quote_plus(sys.stdin.read()))')

# 2. Construct and EXPORT DATABASE_URL
if [ "$DB_TYPE" = "sqlite" ]; then
    if [ -d "/custom-app" ]; then
        DB_URL="file:/data/custom-app.sqlite"
    else
        DB_URL="file:./dev.db"
    fi
    echo "Constructed DATABASE_URL for SQLite: $DB_URL"
elif [ "$DB_TYPE" = "mysql" ]; then
    DB_URL="mysql://${DB_USER}:${ENCODED_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    echo "Constructed DATABASE_URL for MySQL: mysql://${DB_USER}:****@${DB_HOST}:${DB_PORT}/${DB_NAME}"
else
    # Default to postgresql
    DB_TYPE="postgresql"
    DB_URL="postgresql://${DB_USER}:${ENCODED_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
    echo "Constructed DATABASE_URL for PostgreSQL: postgresql://${DB_USER}:****@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
fi

export DATABASE_URL="$DB_URL"

# 3. Set Schema Path and generate .env
ENV_PATH="./src/app/.env"
APP_DIR="./src/app"
if [ -d "/custom-app" ]; then
    ENV_PATH="/custom-app/.env"
    APP_DIR="/custom-app"
fi

echo "Generating .env at $ENV_PATH..."
cat <<EOF > "$ENV_PATH"
# Auto-generated by startScript.sh
DATABASE_URL="$DB_URL"
PORT=$APP_PORT
NODE_ENV=$APP_ENV
TZ=$APP_TZ
EOF
echo ".env generated successfully."

# 4. Modify Prisma Provider dynamically based on DB_TYPE
SCHEMA_PATH="$APP_DIR/prisma/schema.prisma"
if [ -f "$SCHEMA_PATH" ]; then
    echo "Updating Prisma provider to $DB_TYPE..."
        # Replace provider only inside the datasource db block (avoid touching generator provider)
        awk -v db="$DB_TYPE" '
            BEGIN { in_db = 0 }
            /^datasource[[:space:]]+db[[:space:]]*\{/ { in_db = 1 }
            in_db && /^[[:space:]]*provider[[:space:]]*=/ {
                sub(/provider[[:space:]]*=[[:space:]]*"[^"]+"/, "provider = \"" db "\"")
                in_db = 0
            }
            { print }
        ' "$SCHEMA_PATH" > "$SCHEMA_PATH.tmp" && mv "$SCHEMA_PATH.tmp" "$SCHEMA_PATH"
fi

# 5. Application Run Logic
if [ -d "/custom-app" ]; then
    echo "Running in container mode..."
    cd /custom-app

    echo "Running Prisma generate (client sync) and database schema pushing..."
    # Ensure client matches the active provider
    npx prisma generate
    
    # "db push" syncs schema to DB without needing SQL migration files specific to one engine
    npx prisma db push --accept-data-loss
    
    # Start Application
    echo "Starting NestJS application..."
    exec node dist/main.js
else
    echo "Running in local mode. .env generated."
    echo "You are using DB_TYPE=$DB_TYPE"
    echo "To update Prisma locally, please run:"
    echo "  cd src/app && npx prisma generate && npx prisma db push"
    echo "Then start app with 'npm run start:dev' inside src/app."
fi
